apiVersion: apps/v1
kind: Deployment
metadata:
  name: wopi-backend
  namespace: wopi-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wopi-backend
  template:
    metadata:
      labels:
        app: wopi-backend
    spec:
      containers:
        - name: backend
          image: 116839935550.dkr.ecr.us-east-2.amazonaws.com/test-hyl-hob:backend
          ports:
            - containerPort: 5001
          env:
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:5001"
            - name: Registration__Registrationdb
              valueFrom:
                secretKeyRef:
                  name: wopi-database-secret
                  key: connection_string
            - name: Registration__Redis
              valueFrom:
                secretKeyRef:
                  name: wopi-redis-secret
                  key: redis_connection_string
            - name: ConnectionStrings__Registration
              valueFrom:
                secretKeyRef:
                  name: wopi-database-secret
                  key: connection_string
