apiVersion: v1
kind: Service
metadata:
  name: wopi-backend-service
  namespace: wopi-services
spec:
  type: ClusterIP
  selector:
    app: wopi-backend
  ports:
    - port: 5001
      targetPort: 5001
