apiVersion: v1
kind: Service
metadata:
  name: wopi-server-service
  namespace: wopi-services
spec:
  type: ClusterIP
  selector:
    app: wopi-server
  ports:
    - port: 8080
      targetPort: 8080
