apiVersion: v1
kind: Service
metadata:
  name: wopi-frontend-service
  namespace: wopi-services
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0b06351ae3673d696,subnet-0a56f5f1fd90e613d"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-2:116839935550:certificate/f06021bc-6349-44e0-b62e-ba946000a8fc"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"

spec:
  type: LoadBalancer
  selector:
    app: wopi-frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
    - name: https
      port: 443
      targetPort: 3000
      protocol: TCP
